### ISSUE TITLE
Invalid TLS certificate detected

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCommander#63]
Hi 
Unfortunatly i got Invalid TLS certificate detected.

./meshcmd --actionfile meshaction
Invalid TLS certificate detected.

 ./websocat_linux64 -q -uU wss://XXX.XX:443/meshrelay.ashx 2> /dev/null; echo  $?
0

Can we disable TLS verification and know why we got errors

**Comment by gaalos** [comment]
Any update please ?

**Comment by risturiz** [comment]
Hi, im getting the same ( behind Nginx Proxy Manager )... Any idea to debug this? Thanks.

**Comment by Souheib-khiter** [comment]
HEllo

I'm getting the same issue

**Comment by smudge1977** [comment]
Seems a common issue - I have this too

**Comment by pierrecorsini** [comment]
Same here, I have not foud a solution yet.

**Comment by D4rk4** [comment]
Also this issue with caddy

**Comment by masscream** [comment]
+1

**Comment by si458** [comment]
if anybody is happy to provide access to their environment so i can take a look into this issue for them i can help
please email myself (check my github profile for email) OR si458 on discord or telegram

**Comment by antipode-mj** [comment]
I'm happy to provide an access. I contacted si458 in private.

> if anybody is happy to provide access to their environment so i can take a look into this issue for them i can help please email myself (check my github profile for email) OR si458 on discord or telegram

**Comment by antipode-mj** [comment]
We've had a remote session today and si458 was able to reproduce the issue. So it's confirmed but we do not see what is happening. He will have deeper look at it in his dev environment. It was a pleasure to participate at my small scale.

**Comment by antipode-mj** [comment]
Dear all, 

@si458 was able to track down the issue and it's related to the certificate type being ECDSA (new and default type for SWAG as in my environment).
To simplify the issue, MC does not fully support ecdsa, it requires RSA. I quote @si458 
_when meshcentral checks the certurl, it stores the hash as rsa, but when meshcmd checks the cert from swag (nginx/certbot) its given an ecdsa cert and then passed that to meshcentral, so meshcentral goes WTF IS THAT!!! hense the bad cert, so it will need proper investigating to get it fixed_

So we have a proper workaround, it's to force the certificate type to be RSA instead of ECDSA whitch is the default now for LetsEncrypt. There is a lot fo ways of doing this depending of your certbot/proxy.

I'm using https://docs.linuxserver.io/images/docker-swag/ and I had to change these values to force the certificate recreation:
In the file `docker-compose.yml` I've added the `CERTPROVIDER=zerossl` environment variable (I've had an old compose file missig this value ). Changing the provider will force the certificate the container to fully recreate the certificates. 
And in the file `config/etc/letsencrypt/cli.ini` add this line `key-type=rsa`.

So the quick workaround steps goes like this :

1. stop the SWAG container `docker compose down`
2. edit the `docker-compose.yml` file
3. edit the `config/etc/letsencrypt/cli.ini`file
4. start the container with `docker compose up -d`
5. watch for the certificate recreation and healthy container startup with `docker compose logs -f`

I hope this helps. This is all @si458 work, I have no credits here just reporting back his findings and my specific setup edits. Thanks a lot for this workaround.

``

**Comment by risturiz** [comment]
So support for ECDSA should  be new feature request? Or not planned?

**Comment by si458** [comment]
@risturiz at the moment the list is longer than my arm, so it will be looked at at some point! Just not sure when at the moment

**Comment by risturiz** [comment]
> [@risturiz](https://github.com/risturiz) at the moment the list is longer than my arm, so it will be looked at at some point! Just not sure when at the moment

Don't worry... Its not a blocker issue, take your time :-) ... Actually is good to know the problem is solved with RSA, so we don't need to test anymore until the ECDSA support.

**Comment by mgutt** [comment]
Sadly Nginx Proxy Manager still does not allow selecting the algorithm:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3354

But I found a trick:
- download `meshaction.txt`
- remove the `serverId` line
- add a fake password (or the real one, does not matter)
- execute `mescmd` with the modified `meshaction.txt`

Now, instead of the "Invalid TLS cert" error message, we get the needed hash:
>Server TLS hash: F8E6DF1D6CF1...

Replace the `serverHttpsHash` against the returned hash and it works 😁
